"use client"

import { useEffect, useState } from "react"
import { motion } from "framer-motion"
import NavBar from "@/components/NavBar"
import Scrollbar from "@/components/Scrollbar"
import { Github, Linkedin, Mail } from "lucide-react"
import { Button } from "@/components/ui/button"

export default function Home() {
  const [imageLoaded, setImageLoaded] = useState(false)

  useEffect(() => {
    const img = new Image()
    img.src = "/profile.jpg"
    img.onload = () => setImageLoaded(true)
    img.crossOrigin = "anonymous"
  }, [])

  return (
    <div className="min-h-screen flex flex-col">
      <NavBar />
      <Scrollbar />

      <main className="flex-1 flex flex-col">
        {/* Hero Section */}
        <section className="flex-1 flex items-center justify-center px-4 py-12">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="w-full max-w-4xl mx-auto"
          >
            <div className="flex flex-col-reverse lg:flex-row items-center lg:items-start gap-8 lg:gap-12">
              <div className="w-full lg:w-3/4 space-y-4">
                <motion.h1
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ duration: 0.5, delay: 0.2 }}
                  className="text-4xl md:text-5xl font-bold font-montserrat"
                >
                  Sushil Regmi
                </motion.h1>

                <motion.div
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ duration: 0.5, delay: 0.3 }}
                  className="text-xl text-muted-foreground"
                >
                  Web developer lead at{" "}
                  <span className="font-bold cursor-pointer hover:text-primary transition-colors">Ghar</span>
                </motion.div>

                <motion.div
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ duration: 0.5, delay: 0.4 }}
                  className="mt-6 space-y-4"
                >
                  <p className="font-medium">
                    <span className="font-bold">Here is my description generated by Github's copilot</span>
                  </p>

                  <p className="text-muted-foreground leading-relaxed">
                    I am a web developer and I am currently working as a lead at Ghar. I have been coding for the past 3
                    years and I have worked on multiple projects. I have experience in working with React, Node, and
                    Express. I have also worked with databases like MongoDB and SQL. I am also familiar with cloud
                    services like AWS and Azure. I am always looking to learn new things and improve my skills.
                  </p>

                  <div className="pt-4 flex gap-4">
                    <Button variant="outline" size="lg" className="hover:cursor-pointer rounded-full">
                      View My Work
                    </Button>
                    <Button size="lg" className="hover:cursor-pointer rounded-full">
                      Contact Me
                    </Button>
                  </div>
                </motion.div>
              </div>

              <motion.div
                initial={{ opacity: 0, scale: 0.8 }}
                animate={{ opacity: imageLoaded ? 1 : 0, scale: imageLoaded ? 1 : 0.8 }}
                transition={{ duration: 0.5 }}
                className="relative"
              >
                <div className="w-28 h-28 md:w-36 md:h-36 lg:w-48 lg:h-48 rounded-full overflow-hidden border-4 border-primary/20 shadow-xl">
                  {imageLoaded ? (
                    <img src="/profile.jpg" alt="Sushil Regmi" className="w-full h-full object-cover" />
                  ) : (
                    <div className="w-full h-full bg-muted animate-pulse"></div>
                  )}
                </div>

                <div className="absolute -bottom-2 -right-2 w-8 h-8 md:w-10 md:h-10 bg-primary rounded-full flex items-center justify-center text-white">
                  <span className="text-xs md:text-sm font-bold">3+</span>
                </div>
              </motion.div>
            </div>
          </motion.div>
        </section>
      </main>

      <footer className="py-8 border-t">
        <div className="container mx-auto px-4">
          <div className="flex flex-col md:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-2">
              <Button variant="outline" size="sm" asChild>
                <a href="https://www.linkedin.com/in/sushil-regmi-1a1b5b1b1/">About Me</a>
              </Button>
            </div>

            <div className="flex items-center gap-4">
              <Button variant="ghost" size="icon" asChild>
                <a href="https://www.linkedin.com/in/sushil-regmi-1a1b5b1b1/" aria-label="LinkedIn">
                  <Linkedin className="h-5 w-5" />
                </a>
              </Button>
              <Button variant="ghost" size="icon" asChild>
                <a href="https://github.com/" aria-label="GitHub">
                  <Github className="h-5 w-5" />
                </a>
              </Button>
              <Button variant="ghost" size="icon" asChild>
                <a href="mailto:contact@example.com" aria-label="Email">
                  <Mail className="h-5 w-5" />
                </a>
              </Button>
            </div>

            <div className="text-sm text-muted-foreground">
              © {new Date().getFullYear()} Sushil Regmi. All rights reserved.
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}
