import NavBar from "./NavBar";
import "./Home.css";

const Home = () => {
  return (
    <div>
      <NavBar />
      <div className="HomeContainer absolute top-1/2 left-1/2 max-w-2/5 m-1/2 max-h-2/ bg-white transform translate-x-[-50%] translate-y-[-50%]">
        <div className="namedescimg w-3/4 flex row-auto">
          <div className="namedesc w-3/4">

          <h1 className="name w-3/4 text-Montserrat font-bold">Sushil Regmi</h1>
          <br />
          <div className="subname w-3/4 ">
            Web developer lead at{" "}
            <span className="subname cursor-pointer font-bold">Ghar </span>
          </div>
          <br />
          <p className="namedesc text-justify">
            <span className="subname subname cursor-pointer font-bold">
              Here is my description generated by copilot,
              <br />
            </span>
            <br />I am a web developer and I am currently working as a lead at
            Ghar. I have been coding for the past 3 years and I have worked on
            multiple projects. I have experience in working with React, Node,
            and Express. I have also worked with databases like MongoDB and SQL.
            I am also familiar with cloud services like AWS and Azure. I am
            always looking to learn new things and improve my skills.
          </p>
        </div>
      <img className="profileimage w-40 h-40 mx-auto " src="./Profile.jpg" alt="" />
          </div>
      </div>
    </div>
  );
};

export default Home;
