import NavBar from "./NavBar";
import "./Home.css";
import { useEffect, useState } from "react";
import Scrollbar from "./Scrollbar";

const Home = () => {
  const [imageLoaded, setImageLoaded] = useState(false);

  useEffect(() => {
    const img = new Image();
    img.src = "./profile 2.jpg";
    img.onload = () => setImageLoaded(true);
  }, []);

  return (
    <div  >
        
      <NavBar />
      <Scrollbar/>
      <div className="HeaderFooter felx flex-col gap-96 overflow-auto ">
        <div className="MiddleContainer static  top-0 left-0 flex flex-col h-screen w-full overflow-auto   ">
          <div className="HomeContainer   absolute top-1/2 left-1/2  w-11/12 max-w-4xl m-4 p-4 lg:max-w-2/5 m-1/2 max-h-2    transform translate-x-[-48%] translate-y-[-50%]">
            <div className="namedescimg  w-full flex justify-center flex-col-reverse sm:flex-col-reverse lg:flex-row  row-auto">
              <div className="namedesc w-3/4">
                <h1 className="name w-3/4 text-Montserrat font-bold">
                  Sushil Regmi
                </h1>
                <br />
                <div className="subname w-3/4 ">
                  Web developer lead at{" "}
                  <span className="subname cursor-pointer font-bold">
                    Ghar{" "}
                  </span>
                </div>
                <br />
                <p className="namedesc text-justify">
                  <span className=" mt-2 place-content-center subname subname cursor-pointer font-bold">
                    Here is my description generated by Github's opilot,
                    <br />
                  </span>
                  <br />I am a web developer and I am currently working as a
                  lead at Ghar. I have been coding for the past 3 years and I
                  have worked on multiple projects. I have experience in working
                  with React, Node, and Express. I have also worked with
                  databases like MongoDB and SQL. I am also familiar with cloud
                  services like AWS and Azure. I am always looking to learn new
                  things and improve my skills.
                </p>
              </div>
              <img
                className={`profileimage    lg:w-40 lg:h-40 sm:w-28 sm:h-28 w-28 h-28 mb-10 lg:mb-0 mx-auto ${
                  imageLoaded ? "visible" : "invisible"
                }`}
                src="./Profile.jpg"
                alt=""
              />
            </div>
          </div>
        </div>
        <div className="Footer  bottom-0 left-0 flex flex-col gap-2   h-28 text-center w-full ">
          <div className="me">
            <a
              href="
            https://www.linkedin.com/in/sushil-regmi-1a1b5b1b1/"
            >
              <button className="aboutme">About Me</button>
            </a>
          </div>
          <div className="Social">
            <a href="https://www.linkedin.com/in/sushil-regmi-1a1b5b1b1/">
              Linkedin
            </a>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
